# Generated by Django 4.2 on 2023-04-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/fled')),
                ('name', models.CharField(max_length=100)),
                ('years', models.IntegerField()),
                ('proff', models.CharField(max_length=500)),
                ('sport', models.CharField(max_length=100)),
                ('salary', models.FloatField(max_length=100000)),
            ],
        ),
    ]
