# Generated by Django 4.2 on 2023-04-15 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spisock', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='surname',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.set'),
        ),
    ]
