# Generated by Django 4.2 on 2023-04-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_set_alter_surname_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surname',
            name='image',
        ),
        migrations.AddField(
            model_name='set',
            name='image',
            field=models.ImageField(default=1, upload_to='image/fled'),
            preserve_default=False,
        ),
    ]
